services:
  - type: web
    name: railway-booking-backend
    env: python
    buildCommand: cd Backend && pip install -r requirements.txt
    startCommand: cd Backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    
  - type: static
    name: railway-booking-frontend
    buildCommand: echo "No build needed"
    staticPublishPath: ./Frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html